export const templates = [
    {
        name: "الافتراضي (Default)",
        state: {
            thumbnail: "img/backgrounds/bg1.webp",
            blur: 0,
            zoom: 100,
            overlayOpacity: 0.5,
            fontSize: 75,
            textY: 50,
            shadowBlur: 15,
            transShadowBlur: 5,
            animType: 'fade',
            animIntensity: 30,
            reverbEnabled: false,
            reverbIntensity: 0.4,
            showSurahName: false,
            showWaveform: false,
            showWatermark: false,
            showTarteelLogo: true, // Default template should show translation
            showTranslation: true,
            showBasmala: false,
            mediaType: 'image',
            backgroundUrl: "img/backgrounds/bg1.webp",
        },
        ui: {
            fontVersion: 'v1',
            textColor: '#ffffff',
            shadowColor: '#000000',
            transTextColor: '#ffffff',
            transShadowColor: '#000000',
            waveformColor: '#ffffff',
        }
    },
    {
        name: "داكن وأنيق (Modern Dark)",
        state: {
            thumbnail: "img/backgrounds/bg4.webp",
            blur: 8,
            zoom: 110,
            overlayOpacity: 0.6,
            fontSize: 85,
            textY: 50,
            shadowBlur: 25,
            transShadowBlur: 10,
            animType: 'slide',
            animIntensity: 20,
            reverbEnabled: true,
            reverbIntensity: 0.3,
            showSurahName: true,
            surahY: 90,
            showWaveform: true, // Disable translation for this template
            showTranslation: false,
            waveformY: 80,
            showTarteelLogo: true,
            showBasmala: true,
            mediaType: 'image',
            backgroundUrl: "img/backgrounds/bg4.webp",
        },
        ui: {
            fontVersion: 'v2',
            textColor: '#FFFFFF',
            shadowColor: '#000000',
            transTextColor: '#ffffff',
            transShadowColor: '#000000',
            waveformColor: '#FFFFFF',
            basmalaColor: '#FFFFFF',
            basmalaShadowColor: '#000000',
        }
    },
    {
        name: "مشرق ونقي (Clean Light)",
        description: "خلفية مسجد بيضاء نقية مع خط المصحف الكلاسيكي وألوان كحلية هادئة.",
        state: {
            thumbnail: "img/backgrounds/bg6.webp",
            blur: 0,
            zoom: 110,
            overlayOpacity: 0.1,
            fontSize: 90,
            textY: 45,
            shadowBlur: 15,
            transShadowBlur: 5,
            animType: 'zoom',
            animIntensity: 10,
            reverbEnabled: false,
            reverbIntensity: 0.2,
            showSurahName: true,
            surahY: 90,
            showWaveform: false, // Disable translation for this template
            showTranslation: false,
            showTarteelLogo: true,
            showBasmala: false,
            mediaType: 'image',
            backgroundUrl: "img/backgrounds/bg6.webp",
        },
        ui: {
            fontVersion: 'mushaf',
            textColor: '#FFFFFF',
            shadowColor: '#000000',
            transTextColor: '#ffffff',
            transShadowColor: '#000000',
            surahColor: '#FFFFFF'
        }
    },
    {
        name: "سينمائي (Cinematic)",
        description: "خلفية سينمائية ليلية مع خط عريض ولون ذهبي جذاب.",
        state: {
            thumbnail: "img/backgrounds/bg2.webp",
            blur: 5,
            zoom: 120,
            overlayOpacity: 0.4,
            fontSize: 100,
            textY: 50,
            shadowBlur: 20,
            transShadowBlur: 5,
            animType: 'blur',
            animIntensity: 40,
            reverbEnabled: true,
            reverbIntensity: 0.6,
            showTranslation: false,
            mediaType: 'image',
            backgroundUrl: "img/backgrounds/bg2.webp",
        },
        ui: {
            fontVersion: 'pt_bold',
            textColor: '#FFC300',
            shadowColor: '#000000',
            transTextColor: '#ffffff',
        }
    }
];